<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Sales Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            background-color: #f9f9f9;
            margin: 0;
            padding: 0;
        }

        h2 {
            font-size: 24px;
            text-align: center;
            margin-top: 30px;
            color: #333;
        }

        .report-container {
            width: 100%;
            max-width: 900px;
            margin: 30px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        p {
            font-size: 14px;
            text-align: center;
            color: #555;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 10px 15px;
            text-align: left;
        }

        th {
            background-color: #4CAF50;
            color: white;
            font-weight: bold;
        }

        td {
            background-color: #f9f9f9;
        }

        td.text-right {
            text-align: right;
        }

        .total {
            font-size: 18px;
            margin-top: 30px;
            font-weight: bold;
            text-align: right;
        }

        .footer {
            font-size: 12px;
            text-align: center;
            margin-top: 20px;
            color: #777;
        }

        .no-data {
            font-style: italic;
            text-align: center;
            color: #d9534f;
        }
    </style>
</head>

<body>

    <div class="report-container">
        <h2>Sales Report</h2>
        <p>Month: {{ \Carbon\Carbon::create()->month((int) $month)->format('F') }} {{ $year }}</p>

        <table>
            <thead>
                <tr>
                    <th>Delivery Date</th>
                    <th>Order By</th>
                    <th>Quantity</th>
                    <th>Total (₱)</th>
                </tr>
            </thead>
            <tbody>
                @forelse($sales as $sale)
                    <tr>
                        <td>
                            {{ optional($sale->order)?->delivery_date
                                ? \Carbon\Carbon::parse($sale->order->delivery_date)->format('F j, Y')
                                : 'N/A' }}
                        </td>
                        <td>
                            @php $details = $sale->order?->orderDetails?->first(); @endphp
                            {{ $details?->name ?? 'N/A' }}
                        </td>
                        <td>{{ $sale->order?->orderDetails?->sum('quantity') ?? 0 }}</td>
                        <td class="text-right">{{ number_format($sale->amount_due, 2) }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="4" class="no-data">No records found for this period.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>

        <p class="total">Total Revenue: ₱{{ number_format($totalRevenue, 2) }}</p>

        <p class="footer">Generated by the Sales Reporting System. All rights reserved.</p>
    </div>

</body>

</html>
